### ISSUE TITLE
serverless-(dev|prod).env.yml missing in service1

### ISSUE THREAD

**Issue by philiiiiiipp** [MatiasComercio/serverless-sample#1]
I get two warnings while running the sls command within service1

 ```
Serverless Warning --------------------------------------
 
  A valid file to satisfy the declaration 'file(serverless-dev.env.yml)' could not be found.
 
 
 Serverless Warning --------------------------------------
 
  A valid file to satisfy the declaration 'file(service1/serverless-dev.env.yml)' could not be found.
```

I do believe that is because contraire to [Sample project structure image](https://medium.com/wolox-driving-innovation/a-serverless-way-to-serve-more-f8c47e1fd5b1) the two .yaml files are missing in the repository.

**Comment by philiiiiiipp** [comment]
Ok, I should have read the whole readme file more carefully before screaming foul! :-)

**Comment by MatiasComercio** [comment]
Haha, no problem! If you have any further issues, please do not hesitate to contact me!
